package es.uma.informatica.sii.saneka;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SuiteIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSITENCIA_PRUEBAS = "SanekaTest";
  
  @BeforeClass
	public static void setUpBeforeClass() throws Exception {
	  BaseDatos.inicializaBaseDatos(UNIDAD_PERSITENCIA_PRUEBAS);
	}
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void crearAlumnoSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearAlumno.xhtml");
    driver.findElement(By.id("crearAlumno:dni")).sendKeys("1980");
    driver.findElement(By.id("crearAlumno:nombre")).sendKeys("alumnotest");
    driver.findElement(By.id("crearAlumno:apellido1")).sendKeys("alumno");
    driver.findElement(By.id("crearAlumno:apellido2")).sendKeys("test");
    driver.findElement(By.id("crearAlumno:email")).sendKeys("test@test.com");
    driver.findElement(By.id("crearAlumno:btonCrear")).click();
  }
  @Test
  public void crearAlumnoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearAlumno.xhtml");
    driver.findElement(By.id("crearAlumno:dni")).sendKeys("446753A");
    driver.findElement(By.id("crearAlumno:nombre")).sendKeys("Diego");
    driver.findElement(By.id("crearAlumno:apellido1")).sendKeys("Centeno");
    driver.findElement(By.id("crearAlumno:email")).sendKeys("07143291@uma.es");
    driver.findElement(By.id("crearAlumno:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearAlumno:errorDni")).getText(), is("El alumno ya existe"));
  }
  @Test
  public void crearAsignaturaExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearAsignatura.xhtml");
    driver.findElement(By.id("crearAsignatura:referencia")).sendKeys("232");
    driver.findElement(By.id("crearAsignatura:cod")).sendKeys("101");
    driver.findElement(By.id("crearAsignatura:ofer:0")).click();
    driver.findElement(By.id("crearAsignatura:cTeoria")).sendKeys("6");
    driver.findElement(By.id("crearAsignatura:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearAsignatura:errorRef")).getText(), is("La asignatura ya existe"));
  }
  @Test
  public void crearAsignaturaSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearAsignatura.xhtml");
    driver.findElement(By.id("crearAsignatura:referencia")).sendKeys("6464");
    driver.findElement(By.id("crearAsignatura:cod")).sendKeys("410");
    driver.findElement(By.id("crearAsignatura:ofer:0")).click();
    driver.findElement(By.id("crearAsignatura:cTeoria")).sendKeys("12");
    driver.findElement(By.id("crearAsignatura:btonCrear")).click();
  }
  @Test
  public void crearCentroExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearCentro.xhtml");
    driver.findElement(By.id("crearCentro:id")).sendKeys("123");
    driver.findElement(By.id("crearCentro:nombre")).sendKeys("informatica");
    driver.findElement(By.id("crearCentro:direccion")).sendKeys("avenida de andalucia n11");
    driver.findElement(By.id("crearCentro:telefono")).sendKeys("23446");
    driver.findElement(By.id("crearCentro:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearCentro:errorId")).getText(), is("El centro ya existe"));
  }
  @Test
  public void crearCentroSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearCentro.xhtml");
    driver.findElement(By.id("crearCentro:id")).sendKeys("1234");
    driver.findElement(By.id("crearCentro:nombre")).sendKeys("test");
    driver.findElement(By.id("crearCentro:direccion")).sendKeys("test");
    driver.findElement(By.id("crearCentro:telefono")).sendKeys("1234321");
    driver.findElement(By.id("crearCentro:btonCrear")).click();
  }
  @Test
  public void crearClaseExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearClase.xhtml");
    driver.findElement(By.id("crearClase:dia")).sendKeys("23");
    driver.findElement(By.id("crearClase:horaInicio")).sendKeys("8:45");
    driver.findElement(By.id("crearClase:grupoId")).sendKeys("420");
    driver.findElement(By.id("crearClase:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearClase:errorClase")).getText(), is("La clase ya existe"));
  }
  @Test
  public void crearClaseSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearClase.xhtml");
    driver.findElement(By.id("crearClase:dia")).sendKeys("6");
    driver.findElement(By.id("crearClase:horaInicio")).sendKeys("08");
    driver.findElement(By.id("crearClase:grupoId")).sendKeys("420");
    driver.findElement(By.id("crearClase:horaFin")).sendKeys("14");
    driver.findElement(By.id("crearClase:btonCrear")).click();
  }
  @Test
  public void crearClaseSinGrupo() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearClase.xhtml");
    driver.findElement(By.id("crearClase:dia")).sendKeys("3");
    driver.findElement(By.id("crearClase:horaInicio")).sendKeys("15");
    driver.findElement(By.id("crearClase:grupoId")).sendKeys("111111");
    driver.findElement(By.id("crearClase:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearClase:errorGrupo")).getText(), is("El grupo no se ha podido encontrar"));
  }
  @Test
  public void crearExpedienteExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearExpediente.xhtml");
    driver.findElement(By.id("crearExpediente:titulacion")).sendKeys("1234");
    driver.findElement(By.id("crearExpediente:numExpediente")).sendKeys("12345");
    driver.findElement(By.id("crearExpediente:dni")).sendKeys("446753A");
    driver.findElement(By.id("crearExpediente:activo:0")).click();
    driver.findElement(By.id("crearExpediente:crea")).click();
    assertThat(driver.findElement(By.id("crearExpediente:errorExp")).getText(), is("El expediente ya existe"));
  }
  @Test
  public void crearGrupoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearGrupo.xhtml");
    driver.findElement(By.id("crearGrupo:id")).sendKeys("420");
    driver.findElement(By.id("crearGrupo:titulacion")).sendKeys("1234");
    driver.findElement(By.id("crearGrupo:curso")).sendKeys("3");
    driver.findElement(By.id("crearGrupo:letra")).sendKeys("B");
    driver.findElement(By.id("crearGrupo:turno")).sendKeys("tarde");
    driver.findElement(By.id("crearGrupo:ngles:1")).click();
    driver.findElement(By.id("crearGrupo:visible:0")).click();
    driver.findElement(By.id("crearGrupo:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearGrupo:errorGrupo")).getText(), is("El grupo ya existe"));
  }
  @Test
  public void crearMatriculaExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearMatricula.xhtml");
    driver.findElement(By.id("crearMatricula:nExp")).sendKeys("12345");
    driver.findElement(By.id("crearMatricula:cursoA")).sendKeys("3");
    driver.findElement(By.id("crearMatricula:fechaMatrícula")).sendKeys("12/09/2020");
    driver.findElement(By.id("crearMatricula:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearMatricula:errorMatricula")).getText(), is("La matricula ya existe"));
  }
  @Test
  public void crearOptativaExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearOptativa.xhtml");
    driver.findElement(By.id("crearOptativa:referencia")).sendKeys("233");
    driver.findElement(By.id("crearOptativa:cod")).sendKeys("102");
    driver.findElement(By.id("crearOptativa:ofer:0")).click();
    driver.findElement(By.id("crearOptativa:cTeoria")).sendKeys("6");
    driver.findElement(By.id("crearOptativa:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearOptativa:errorId")).getText(), is("La optativa ya existe"));
  }
  @Test
  public void crearTitulacionExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearTitulacion.xhtml");
    driver.findElement(By.id("crearTitulacion:dC")).sendKeys("123");
    driver.findElement(By.id("crearTitulacion:codTitu")).sendKeys("1234");
    driver.findElement(By.id("crearTitulacion:cred")).sendKeys("6");
    driver.findElement(By.id("crearTitulacion:nombre")).sendKeys("infor");
    driver.findElement(By.id("crearTitulacion:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearTitulacion:errorId")).getText(), is("La titulacion ya existe"));
  }
  @Test
  public void crearGrupoSinTitulacion() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearGrupo.xhtml");
    driver.findElement(By.id("crearGrupo:id")).sendKeys("460");
    driver.findElement(By.id("crearGrupo:titulacion")).sendKeys("1111");
    driver.findElement(By.id("crearGrupo:curso")).sendKeys("4");
    driver.findElement(By.id("crearGrupo:letra")).sendKeys("A");
    driver.findElement(By.id("crearGrupo:turno")).sendKeys("M");
    driver.findElement(By.id("crearGrupo:visible:0")).click();
    driver.findElement(By.id("crearGrupo:ingles:1")).click();
    driver.findElement(By.id("crearGrupo:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearGrupo:errorTitulacion")).getText(), is("La titulacion no se ha podido encontrar"));
  }
  @Test
  public void crearMatriculaSinExpediente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearMatricula.xhtml");
    driver.findElement(By.id("crearMatricula:nExp")).sendKeys("11111");
    driver.findElement(By.id("crearMatricula:cursoA")).sendKeys("4");
    driver.findElement(By.id("crearMatricula:fechaMatrícula")).sendKeys("14/07/2019");
    driver.findElement(By.id("crearMatricula:btonCrear")).click();
    assertThat(driver.findElement(By.id("crearMatricula:errorExpediente")).getText(), is("El expediente no se ha podido encontrar"));
  }
  @Test
  public void crearExpedienteSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearExpediente.xhtml");
    driver.findElement(By.id("crearExpediente:titulacion")).sendKeys("1234");
    driver.findElement(By.id("crearExpediente:numExpediente")).sendKeys("99999");
    driver.findElement(By.id("crearExpediente:dni")).sendKeys("770341P");
    driver.findElement(By.id("crearExpediente:activo:0")).click();
    driver.findElement(By.id("crearExpediente:crea")).click();
  }
  @Test
  public void crearGrupoSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearGrupo.xhtml");
    driver.findElement(By.id("crearGrupo:id")).sendKeys("450");
    driver.findElement(By.id("crearGrupo:titulacion")).sendKeys("1234");
    driver.findElement(By.id("crearGrupo:curso")).sendKeys("4");
    driver.findElement(By.id("crearGrupo:letra")).sendKeys("A");
    driver.findElement(By.id("crearGrupo:turno")).sendKeys("M");
    driver.findElement(By.id("crearGrupo:ingles:1")).click();
    driver.findElement(By.id("crearGrupo:visible:0")).click();
    driver.findElement(By.id("crearGrupo:btonCrear")).click();
  }
  @Test
  public void crearMatriculaSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearMatricula.xhtml");
    driver.findElement(By.id("crearMatricula:cursoA")).sendKeys("4");
    driver.findElement(By.id("crearMatricula:fechaMatrícula")).sendKeys("13/08/2021");
    driver.findElement(By.id("crearMatricula:nExp")).sendKeys("12345");
    driver.findElement(By.id("crearMatricula:btonCrear")).click();
  }
  @Test
  public void crearOptativaSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearOptativa.xhtml");
    driver.findElement(By.id("crearOptativa:referencia")).sendKeys("8888");
    driver.findElement(By.id("crearOptativa:cod")).sendKeys("450");
    driver.findElement(By.id("crearOptativa:ofer:0")).click();
    driver.findElement(By.id("crearOptativa:cTeoria")).sendKeys("12");
    driver.findElement(By.id("crearOptativa:btonCrear")).click();
  }
  @Test
  public void crearTitulacionSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/crearTitulacion.xhtml");
    driver.findElement(By.id("crearTitulacion:codTitu")).sendKeys("12356");
    driver.findElement(By.id("crearTitulacion:nombre")).sendKeys("lul");
    driver.findElement(By.id("crearTitulacion:btonCrear")).click();
  }
  
  @Test
  public void eliminarAlumnoNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarAlumno.xhtml");
    driver.findElement(By.id("eliminarAlumno:dni")).sendKeys("4444444");
    driver.findElement(By.id("eliminarAlumno:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarAlumno:errorDni")).getText(), is("El alumno no se ha podido encontrar"));
  }
  @Test
  public void eliminarAlumnoSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarAlumno.xhtml");
    driver.findElement(By.id("eliminarAlumno:dni")).sendKeys("374147G");
    driver.findElement(By.id("eliminarAlumno:btonEliminar")).click();
  }
  @Test
  public void eliminarAsignaturaNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarAsignatura.xhtml");
    driver.findElement(By.id("eliminarAsignatura:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarAsignatura:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarAsignatura:ref")).sendKeys("88888");
    driver.findElement(By.id("eliminarAsignatura:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarAsignatura:errorRef")).getText(), is("La asignatura no se ha podido encontrar"));
  }
  @Test
  public void eliminarAsignaturaSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarAsignatura.xhtml");
    driver.findElement(By.id("eliminarAsignatura:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarAsignatura:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarAsignatura:ref")).sendKeys("232");
    driver.findElement(By.id("eliminarAsignatura:btonEliminar")).click();
  }
  @Test
  public void eliminarCentroNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarCentro.xhtml");
    driver.findElement(By.id("eliminarCentro:centroId")).sendKeys("99999");
    driver.findElement(By.id("eliminarCentro:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarCentro:errorId")).getText(), is("El centro no se ha podido encontrar"));
  }
  @Test
  public void eliminarCentroSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarCentro.xhtml");
    driver.findElement(By.id("eliminarCentro:centroId")).sendKeys("123");
    driver.findElement(By.id("eliminarCentro:btonEliminar")).click();
  }
  @Test
  public void eliminarClaseNoExistente() {
  }
  @Test
  public void eliminarClaseSatisfactorio() {
  }
  @Test
  public void eliminarClaseSinGrupo() {
  }
  @Test
  public void eliminarExpedienteNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarExpediente.xhtml");
    driver.findElement(By.id("eliminarExpediente:titulacion")).sendKeys("1234");
    driver.findElement(By.id("eliminarExpediente:numExpediente")).sendKeys("99999");
    driver.findElement(By.id("eliminarExpediente:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarExpediente:errorExp")).getText(), is("El expediente no se ha podido encontrar"));
  }
  @Test
  public void eliminarExpedienteSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarExpediente.xhtml");
    driver.findElement(By.id("eliminarExpediente:titulacion")).sendKeys("1234");
    driver.findElement(By.id("eliminarExpediente:numExpediente")).sendKeys("12345");
    driver.findElement(By.id("eliminarExpediente:btonEliminar")).click();
  }
  @Test
  public void eliminarGrupoNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarGrupo.xhtml");
    driver.findElement(By.id("eliminarGrupo:titulacion")).sendKeys("1234");
    driver.findElement(By.id("eliminarGrupo:grupoId")).sendKeys("99999");
    driver.findElement(By.id("eliminarGrupo:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarGrupo:errorGrupo")).getText(), is("El grupo no se ha podido encontrar"));
  }
  @Test
  public void eliminarGrupoSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarGrupo.xhtml");
    driver.findElement(By.id("eliminarGrupo:titulacion")).sendKeys("1234");
    driver.findElement(By.id("eliminarGrupo:grupoId")).sendKeys("420");
    driver.findElement(By.id("eliminarGrupo:btonEliminar")).click();
  }
  @Test
  public void eliminarGrupoSinTitulacion() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarGrupo.xhtml");
    driver.findElement(By.id("eliminarGrupo:titulacion")).sendKeys("9999");
    driver.findElement(By.id("eliminarGrupo:grupoId")).sendKeys("420");
    driver.findElement(By.id("eliminarGrupo:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarGrupo:errorTitulacion")).getText(), is("La titulacion no se ha podido encontrar"));
  }
  @Test
  public void eliminarMatriculaNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarMatricula.xhtml");
    driver.findElement(By.id("eliminarMatricula:dni")).sendKeys("446753A");
    driver.findElement(By.id("eliminarMatricula:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarMatricula:dC")).sendKeys("123");
    driver.findElement(By.id("eliminarMatricula:nExp")).sendKeys("12345");
    driver.findElement(By.id("eliminarMatricula:cursoA")).sendKeys("4");
    driver.findElement(By.id("eliminarMatricula:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarMatricula:errorMatricula")).getText(), is("La matricula no se ha podido encontrar"));
  }
  @Test
  public void eliminarMatriculaSastisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarMatricula.xhtml");
    driver.findElement(By.id("eliminarMatricula:dni")).sendKeys("446753A");
    driver.findElement(By.id("eliminarMatricula:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarMatricula:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarMatricula:nExp")).sendKeys("12345");
    driver.findElement(By.id("eliminarMatricula:cursoA")).sendKeys("3");
    driver.findElement(By.id("eliminarMatricula:btonEliminar")).click();
  }
  @Test
  public void eliminarMatriculaSinExpediente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarMatricula.xhtml");
    driver.findElement(By.id("eliminarMatricula:dni")).sendKeys("446753A");
    driver.findElement(By.id("eliminarMatricula:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarMatricula:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarMatricula:nExp")).sendKeys("99999");
    driver.findElement(By.id("eliminarMatricula:cursoA")).sendKeys("3");
    driver.findElement(By.id("eliminarMatricula:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarMatricula:errorExpediente")).getText(), is("El expediente no se ha podido encontrar"));
  }
  @Test
  public void eliminarOptativaNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarOptativa.xhtml");
    driver.findElement(By.id("eliminarOptativa:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarOptativa:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarOptativa:referencia")).sendKeys("999");
    driver.findElement(By.id("eliminarOptativa:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarOptativa:errorId")).getText(), is("La optativa no se ha podido encontrar"));
  }
  @Test
  public void eliminarOptativaSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarOptativa.xhtml");
    driver.findElement(By.id("eliminarOptativa:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarOptativa:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarOptativa:referencia")).sendKeys("233");
    driver.findElement(By.id("eliminarOptativa:btonEliminar")).click();
  }
  @Test
  public void eliminarTitulacionNoExistente() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarTitulacion.xhtml");
    driver.findElement(By.id("eliminarTitulacion:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarTitulacion:codTitu")).sendKeys("99999");
    driver.findElement(By.id("eliminarTitulacion:btonEliminar")).click();
    assertThat(driver.findElement(By.id("eliminarTitulacion:errorId")).getText(), is("La titulacion no se ha podido encontrar"));
  }
  @Test
  public void eliminarTitulacionSatisfactorio() {
    driver.get("http://localhost:8080/jpa.saneka-war/faces/eliminarTitulacion.xhtml");
    driver.findElement(By.id("eliminarTitulacion:idC")).sendKeys("123");
    driver.findElement(By.id("eliminarTitulacion:codTitu")).sendKeys("1234");
    driver.findElement(By.id("eliminarTitulacion:btonEliminar")).click();
  }
}
