package es.uma.informatica.sii.saneka;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SuiteIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSITENCIA_PRUEBAS = "SanekaTest";
  
  @BeforeClass
	public static void setUpBeforeClass() throws Exception {
	  BaseDatos.inicializaBaseDatos(UNIDAD_PERSITENCIA_PRUEBAS);
	}
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginContraseniaIncorrecta() {
    driver.get("http://localhost:8080/jpa.saneka-war/");
    driver.manage().window().setSize(new Dimension(1086, 665));
    driver.findElement(By.id("j_idt5:correo")).sendKeys("tal@uma.es");
    driver.findElement(By.id("j_idt5:password")).sendKeys("123");
    driver.findElement(By.name("j_idt5:j_idt11")).click();
  }
  @Test
  public void loginExitosoAlumno() {
    driver.get("http://localhost:8080/jpa.saneka-war/");
    driver.manage().window().setSize(new Dimension(1086, 665));
    driver.findElement(By.id("j_idt5:correo")).sendKeys("07143291@uma.es");
    driver.findElement(By.id("j_idt5:password")).sendKeys("123");
    driver.findElement(By.name("j_idt5:j_idt11")).click();
    assertThat(driver.getTitle(), is("Encuesta"));
  }
  @Test
  public void loginExitosoSecretaria() {
    driver.get("http://localhost:8080/jpa.saneka-war/");
    driver.manage().window().setSize(new Dimension(1086, 665));
    driver.findElement(By.id("j_idt5:correo")).sendKeys("sec1@uma.es");
    driver.findElement(By.id("j_idt5:password")).sendKeys("123");
    driver.findElement(By.name("j_idt5:j_idt11")).click();
    assertThat(driver.getTitle(), is("Panel de control de Secretaria"));
  }
  @Test
  public void loginUsuarioNoEncontrado() {
    driver.get("http://localhost:8080/jpa.saneka-war/");
    driver.manage().window().setSize(new Dimension(1086, 665));
    driver.findElement(By.id("j_idt5:correo")).sendKeys("tal@uma.es");
    driver.findElement(By.id("j_idt5:password")).sendKeys("123");
    driver.findElement(By.name("j_idt5:j_idt11")).click();
  }
  @Test
  public void paginaIndice() {
    driver.get("http://localhost:8080/jpa.saneka-war/");
    driver.manage().window().setSize(new Dimension(1086, 665));
    assertThat(driver.getTitle(), is("Login"));
  }
}
